export class Usuario{



  public razSocCad: string;
  public cnpjCad: string;
  public endCad: string;
  public cepCad: string;
  public cidadeCad: string;
  public estadoCad: string;
  public socioCad: string;
  public cargoCad: string;
  public cpf1Cad: string;
  public rg1Cad: string;
  public cpf2Cad: string;
  public rg2Cad: string;
  public end2Cad: string;
  public cep2Cad: string;
  public data: string;
  public razSoc: string;
  public cnpj: string;
  public inscEst: string;
  public inscMun: string;
  public fone: string;
  public fone2: string;
  public email: string;
  public nomeFin: string;
  public fone3: string;
  public emailFin: string;
  public cargo: string;
  public contMv: string;
  public cep: string;
  public numero: number;
  public complemento: string;
  public rua: string;
  public bairro: string;
  public cidade: string;
  public estado: string;
  public conta: string;
  public agencia: string;
  public op: number;
  public banco: string;
  public favorecido: string;
  public razSoc3: string;
  public PossCapTecExecCont: boolean;
  public EmpPossProgInteComp: boolean;
  public EmpPossHistEnvFrau: boolean;
  public EmpListCeisCnep: boolean;
  public textarea5: string;
  public textarea6: string;
  public AlgumSocPossVincMv: boolean;
  public textarea7: string;
  public FuncPrestServVinMV: boolean;
  public textarea8: string;
  public AlgumSocFuncPubl: boolean;
  public textarea9: string;
  public AlgumSocConcCargPub : boolean;
  public textarea10: string;
  public AlgumSocConjFuncMv: boolean;
  public textarea11: string;
  public EmpPossRelOutPais: boolean;
  public textarea12: string;
  public EmpUsaIntFechNeg: boolean;
  public textarea13: string;
  public EmpRealizTreinLgpdMv: boolean;
  public EmpPossCertLgpd: boolean;
  public textarea15: string;
  public EmpPossEncarProtDad: boolean;
  public textarea16: string;
  public EmpEnconAptaAvalDanPess: boolean;
  public OsColabTreiCapacLgpd : boolean;
  public DescTecSegAdotPreserLgpd: boolean;
  public textarea19: string;
  public TransfeCompartLgpdAcordLei: boolean;
  public data2: string;
  public nomeLeg: string;
  public rgRep: string;
  public cargoRep: string;


}
